FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app

COPY *.csproj ./

RUN dotnet restore 

COPY . . 

RUN dotnet publish -c Release -o /app/publish

# -------------------------------------

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS prod

WORKDIR /app

COPY --from=build /app/publish .

CMD ["dotnet", "demo.dll"]